signals:
  SNR: 0
  sparsity: 90
  lambda_: 0.1

solvers:
  SCGL:
    alpha: 0.0025
    beta: 60
    initialization_mode: 'QP'
    proximal_mode: 'Proximal-LOG'
    update_frames: True
    SOC: True
    rho: 100
    fix_beta: False
    beta_min: 10
    beta_max: 300
    beta_factor: 5e-2

solver: SCGL
